open Ast

(** Module embedding functions to generate the tools related to the oracle of the studied network protocol implementation. *)

(**
  Get a shell script to capture the syscalls emitted by the implementation by exercising it against an input. The returned string can be directly outputed to a [bash] script in order to launch it. The generated script relies on [strace] to collect syscalls, so it was only tested under Linux.
*)
val generate_get_syscalls_sh : csl_ast -> string

(**
  Get an ocaml program ready to be build taking as input :
  - A directory containing all the commands to test
  - A directory containing all the {b reduced} system calls file associated with all the commands to test (Generated by the script generated by {!val:generate_get_syscalls_sh}).
  - A directory containing all the {b full} system calls file associated with all the commands to test (Generated by the script generated by {!val:generate_get_syscalls_sh}).
  - An {b empty} output directory

  Example of code to compile the generated program:
  {[
    let _ = Sys.command (Filename.quote_command "ocamlc" ["-I"; "+str"; "-I"; "+unix"; "str.cma"; "unix.cma"; "syscall_monitor.ml"; "-o"; "syscall_monitor"]) in
    ()
  ]}
*)
val generate_syscall_monitor_ml : csl_ast -> string